/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Char: typeof import('./src/components/Char.vue')['default']
    Character: typeof import('./src/components/Character.vue')['default']
    Question: typeof import('./src/components/Question.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Word: typeof import('./src/components/Word.vue')['default']
    Workspace: typeof import('./src/components/Workspace.vue')['default']
  }
}
