/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Char: typeof import('./src/components/Char.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    PopBirthdayModal: typeof import('./src/components/PopBirthdayModal.vue')['default']
    Question: typeof import('./src/components/Question.vue')['default']
    Word: typeof import('./src/components/Word.vue')['default']
    Workspace: typeof import('./src/components/Workspace.vue')['default']
  }
}
